# Generated by Django 5.2.7 on 2025-10-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('curriculo_original', models.FileField(upload_to='curriculos/', verbose_name='Arquivo do Currículo')),
                ('texto_do_curriculo', models.TextField(blank=True, null=True, verbose_name='Conteúdo Processado')),
                ('habilidades', models.TextField(blank=True, null=True, verbose_name='Habilidades Extraídas')),
                ('experiencia', models.TextField(blank=True, null=True, verbose_name='Experiência Profissional')),
                ('data_de_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-data_de_upload'],
            },
        ),
    ]
