# Generated by Django 5.2.7 on 2025-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ['-data_de_upload']},
        ),
        migrations.AddField(
            model_name='candidato',
            name='formacao_academica',
            field=models.TextField(blank=True, null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='idiomas',
            field=models.TextField(blank=True, null=True, verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curriculo_original',
            field=models.FileField(upload_to='curriculos/'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='texto_do_curriculo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
