# Generated by Django 5.2.7 on 2025-10-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_candidato_options_candidato_formacao_academica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoExtracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrair_experiencia', models.BooleanField(default=True, verbose_name='Extrair Experiência Profissional')),
                ('extrair_habilidades', models.BooleanField(default=True, verbose_name='Extrair Competências e Habilidades')),
                ('extrair_formacao', models.BooleanField(default=True, verbose_name='Extrair Formação Acadêmica')),
                ('extrair_idiomas', models.BooleanField(default=True, verbose_name='Extrair Idiomas')),
            ],
            options={
                'verbose_name_plural': 'Configurações de Extração',
            },
        ),
    ]
