# Generated by Django 5.2.7 on 2025-10-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Um título para fácil identificação do documento.', max_length=200)),
                ('arquivo_original', models.FileField(upload_to='documentos/')),
                ('texto_do_documento', models.TextField(blank=True, null=True, verbose_name='Conteúdo em Texto')),
                ('entidades_extraidas', models.JSONField(blank=True, null=True, verbose_name='Entidades (JSON)')),
                ('data_de_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_de_upload'],
            },
        ),
    ]
